### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Ha0ran2001** [WangYeWei/YeweiDesign_ts_react#1]
当我 `yarn` 把依赖安装完之后，执行 `yarn build` 出现了这个错误。
已经全局安装了 pnpm。
```
yarn run v1.22.17
$ pnpm run clean && rollup -c

> design-06k4@2.17.10 clean F:\LearnCode\Clone\design-06k4
> rimraf ./dist

[!] TypeError: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getConfigList (F:\LearnCode\Clone\design-06k4\node_modules\rollup\dist\shared\loadConfigFile.js:650:16)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by wangyewei** [comment]
`yarn build:esm`

**Comment by jiaquanchao** [comment]
请问这个是什么原因呀

**Comment by wangyewei** [comment]
> 请问这个是什么原因呀

因为打包命令只配置了`build:esm`，所以执行`build`就会出错。

具体地，执行`build:esm`执行的是`cross-env BABEL_ENV=esm rollup -c`。`rollup -c `命令会告诉`Rollup`命令行工具使用当前目录下的`rollup.config.js`文件作为配置文件来进行打包。通过设置环境变量`BABEL_ENV`，在文件`rollup.config.js`中根据`switch (BABEL_ENV) {}`去return出rollup打包所需的配置。

这个配置是一个对象或者数组，描述了打包出、入口、插件等信息，最终导出。但是由于目前只针对`BABEL_ENV === 'esm'`做了控制，所以当`BABEL_ENV`为除了`'esm'`以外的任何值，或者空值，`rollup.config.js`最终都不会有任何导出，`rollup`无法从中获取必要信息进行打包操作。

当`Rollup`在执行配置文件时会尝试解析默认导出的内容，将其作为配置对象或配置函数使用。但是由于没有导出内容，解析默认导出的结果是`undefined`。当尝试将`undefined`转换为对象时，JavaScript 抛出 `"TypeError: Cannot convert undefined or null to object"` 错误。
