### ISSUE TITLE
如果想每次引入单个组件的时候不引入样式文件如何修改打包策略

### ISSUE THREAD

**Issue by xiaoshan100** [WangYeWei/YeweiDesign_ts_react#3]

**Comment by wangyewei** [comment]
在项目中使用时，样式文件需要手动引入，不会自动引入。如果不想打包单个组件的样式，简单方法可以在`rollup.config.js`中的`externalConfig`进行配置。且不建议将这个项目用在实际生产中...

**Comment by xiaoshan100** [comment]
我的意思是打包后，每个组件的文件里面都有对应的样式文件了，而不是像现在这样 不需要再去手动全部引入一次总的样式文件，比如我只想用一个组件   就只用这一个组件的样式   不需要额外引入全部组件的样式

**Comment by cuiliangl** [comment]
> 我的意思是打包后，每个组件的文件里面都有对应的样式文件了，而不是像现在这样 不需要再去手动全部引入一次总的样式文件，比如我只想用一个组件 就只用这一个组件的样式 不需要额外引入全部组件的样式

我也想这样，有好的方案吗？
期望打包后的目录结构类似于ant 组件库这样的
<img width="312" alt="image" src="https://github.com/wangyewei/design-06k4/assets/25759364/42fb9cce-a7be-448c-92e7-a21f2ad9d967">

**Comment by wangyewei** [comment]
> 我的意思是打包后，每个组件的文件里面都有对应的样式文件了，而不是像现在这样 不需要再去手动全部引入一次总的样式文件，比如我只想用一个组件 就只用这一个组件的样式 不需要额外引入全部组件的样式

See: https://github.com/wangyewei/design-06k4/blob/Devlopment-Version/scripts/build-css.js

**Comment by cuiliangl** [comment]
> > 我的意思是打包后，每个组件的文件里面都有对应的样式文件了，而不是像现在这样 不需要再去手动全部引入一次总的样式文件，比如我只想用一个组件 就只用这一个组件的样式 不需要额外引入全部组件的样式
> 
> See: https://github.com/wangyewei/design-06k4/blob/Devlopment-Version/scripts/build-css.js

我找到解决方式了，一种是自己写了rollup插件，跟你这个差不多，自己编译scss。另一种是把每个组件作为独立入口，这个一开始尝试过，问题是css还是全部打成一个，没有独立拆分。最后发现需要独立配置打包目录，因为css是和js打到同级的。

**Comment by wangyewei** [comment]
> > > 我的意思是打包后，每个组件的文件里面都有对应的样式文件了，而不是像现在这样 不需要再去手动全部引入一次总的样式文件，比如我只想用一个组件 就只用这一个组件的样式 不需要额外引入全部组件的样式
> > 
> > 
> > See: https://github.com/wangyewei/design-06k4/blob/Devlopment-Version/scripts/build-css.js
> 
> 我找到解决方式了，一种是自己写了rollup插件，跟你这个差不多，自己编译scss。另一种是把每个组件作为独立入口，这个一开始尝试过，问题是css还是全部打成一个，没有独立拆分。最后发现需要独立配置打包目录，因为css是和js打到同级的。

编写Rollup插件听起来不错，感兴趣的话欢迎提交pr!
