### ISSUE TITLE
请教打包目录结构

### ISSUE THREAD

**Issue by cuiliangl** [WangYeWei/YeweiDesign_ts_react#4]
怎么能打成这种格式的呢？一个组件对应一个css文件
<img width="339" alt="image" src="https://github.com/wangyewei/design-06k4/assets/25759364/34a64602-a32a-4c0a-893b-e443ed0a3de7">

**Comment by wangyewei** [comment]
Re-execute `pnpm run build`
See: https://github.com/wangyewei/design-06k4/blob/Devlopment-Version/scripts/build-css.js
